name: CI JavaScript

on:
    workflow_dispatch:
    pull_request:

permissions:
    contents: read

env:
    NODE_VERSION: '20'

jobs:
    ci-js:
        name: JavaScript CI
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  cache: 'yarn'
                  cache-dependency-path: 'yarn.lock'

            - name: Install dependencies
              run: yarn install --immutable

            - name: Check types - React app
              working-directory: app
              run: yarn check-types

            - name: Check types - server
              working-directory: server
              run: yarn check-types

            - name: Lint
              run: yarn lint

            - name: Build the React app
              working-directory: app
              run: yarn build

            - name: Build the server app
              working-directory: server
              run: yarn build
